/**
 * Test for all possible types of parameters including LOB's.
 *
 * @param @p_bigint         Test parameter for bigint.
 * @param @p_bit            Test parameter for bit.
 * @param @p_char           Test parameter for char.
 * @param @p_date           Test parameter for date.
 * @param @p_datetime       Test parameter for datetime.
 * @param @p_datetime2      Test parameter for datetime2.
 * @param @p_datetimeoffset Test parameter for datetimeoffset.
 * @param @p_decimal        Test parameter for decimal.
 * @param @p_float          Test parameter for float.
 * @param @p_int            Test parameter for int.
 * @param @p_money          Test parameter for money.
 * @param @p_nchar          Test parameter for nchar.
 * @param @p_numeric        Test parameter for numeric.
 * @param @p_real           Test parameter for real.
 * @param @p_smalldatetime  Test parameter for smalldatetime.
 * @param @p_smallint       Test parameter for smallint.
 * @param @p_smallmoney     Test parameter for smallmoney.
 * @param @p_time           Test parameter for time.
 * @param @p_tinyint        Test parameter for tinyint.
 * @param @p_tst_geography  Test parameter for geography.
 * @param @p_tst_geometry   Test parameter for geometry.
 * @param @p_tst_image      Test parameter for image.
 * @param @p_tst_ntext      Test parameter for ntext.
 * @param @p_tst_text       Test parameter for text.
 * @param @p_tst_xml        Test parameter for xml.
 * @param @p_varchar        Test parameter for varchar.
 */
create procedure dbo.tst_parameter_types02
  @tst_bigint         @dbo.tst_foo1.tst_bigint%type@,
  @tst_int            @dbo.tst_foo1.tst_int%type@,
  @tst_smallint       @dbo.tst_foo1.tst_smallint%type@,
  @tst_tinyint        @dbo.tst_foo1.tst_tinyint%type@,
  @tst_bit            @dbo.tst_foo1.tst_bit%type@,
  @tst_money          @dbo.tst_foo1.tst_money%type@,
  @tst_smallmoney     @dbo.tst_foo1.tst_smallmoney%type@,
  @tst_decimal        @dbo.tst_foo1.tst_decimal%type@,
  @tst_numeric        @dbo.tst_foo1.tst_numeric%type@,
  @tst_float          @dbo.tst_foo1.tst_float%type@,
  @tst_real           @dbo.tst_foo1.tst_real%type@,
  @tst_date           @dbo.tst_foo1.tst_date%type@,
  @tst_datetime       @dbo.tst_foo1.tst_datetime%type@,
  @tst_datetime2      @dbo.tst_foo1.tst_datetime2%type@,
  @tst_datetimeoffset @dbo.tst_foo1.tst_datetimeoffset%type@,
  @tst_smalldatetime  @dbo.tst_foo1.tst_smalldatetime%type@,
  @tst_time           @dbo.tst_foo1.tst_time%type@,
  @tst_char           @dbo.tst_foo1.tst_char%type@,
  @tst_varchar        @dbo.tst_foo1.tst_varchar%type@,
  @tst_text           @dbo.tst_foo1.tst_text%type@,
  @tst_nchar          @dbo.tst_foo1.tst_nchar%type@,
  @tst_nvarchar       @dbo.tst_foo1.tst_nvarchar%type@,
  @tst_ntext          @dbo.tst_foo1.tst_ntext%type@,
  @tst_binary         @dbo.tst_foo1.tst_binary%type@,
  @tst_varbinary      @dbo.tst_foo1.tst_varbinary%type@,
  @tst_image          @dbo.tst_foo1.tst_image%type@,
  @tst_xml            @dbo.tst_foo1.tst_xml%type@,
  @tst_geography      @dbo.tst_foo1.tst_geography%type@,
  @tst_geometry       @dbo.tst_foo1.tst_geometry%type@
-- type: none
as
insert into TST_FOO1( tst_bigint,
                      tst_int,
                      tst_smallint,
                      tst_tinyint,
                      tst_bit,
                      tst_money,
                      tst_smallmoney,
                      tst_decimal,
                      tst_numeric,
                      tst_float,
                      tst_real,
                      tst_date,
                      tst_datetime,
                      tst_datetime2,
                      tst_datetimeoffset,
                      tst_smalldatetime,
                      tst_time,
                      tst_char,
                      tst_varchar,
                      tst_text,
                      tst_nchar,
                      tst_nvarchar,
                      tst_ntext,
                      tst_binary,
                      tst_varbinary,
                      tst_image,
                      tst_xml,
                      tst_geography,
                      tst_geometry )
values( @tst_bigint,
        @tst_int,
        @tst_smallint,
        @tst_tinyint,
        @tst_bit,
        @tst_money,
        @tst_smallmoney,
        @tst_decimal,
        @tst_numeric,
        @tst_float,
        @tst_real,
        @tst_date,
        @tst_datetime,
        @tst_datetime2,
        @tst_datetimeoffset,
        @tst_smalldatetime,
        @tst_time,
        @tst_char,
        @tst_varchar,
        @tst_text,
        @tst_nchar,
        @tst_nvarchar,
        @tst_ntext,
        @tst_binary,
        @tst_varbinary,
        @tst_image,
        @tst_xml,
        @tst_geography,
        @tst_geometry )
        ;

