/**
 * Test for all possible types of parameters excluding LOB's.
 *
 * @param @p_bigint         Test parameter for bigint.
 * @param @p_bit            Test parameter for bit.
 * @param @p_char           Test parameter for char.
 * @param @p_date           Test parameter for date.
 * @param @p_datetime       Test parameter for datetime.
 * @param @p_datetime2      Test parameter for datetime2.
 * @param @p_datetimeoffset Test parameter for datetimeoffset.
 * @param @p_decimal        Test parameter for decimal.
 * @param @p_float          Test parameter for float.
 * @param @p_int            Test parameter for int.
 * @param @p_money          Test parameter for money.
 * @param @p_nchar          Test parameter for nchar.
 * @param @p_numeric        Test parameter for numeric.
 * @param @p_real           Test parameter for real.
 * @param @p_smalldatetime  Test parameter for smalldatetime.
 * @param @p_smallint       Test parameter for smallint.
 * @param @p_smallmoney     Test parameter for smallmoney.
 * @param @p_time           Test parameter for time.
 * @param @p_tinyint        Test parameter for tinyint.
 * @param @p_varchar        Test parameter for varchar.
 */
create procedure tst_parameter_types01
  @p_bigint             @tst_foo1.tst_bigint%type@,
  @p_bit                @tst_foo1.tst_bit%type@,
  @p_char               @tst_foo1.tst_char%type@,
  @p_date               @tst_foo1.tst_date%type@,
  @p_datetime           @tst_foo1.tst_datetime%type@,
  @p_datetime2          @tst_foo1.tst_datetime2%type@,
  @p_datetimeoffset     @tst_foo1.tst_datetimeoffset%type@,
  @p_decimal            @tst_foo1.tst_decimal%type@,
  @p_float              @tst_foo1.tst_float%type@,
  @p_int                @tst_foo1.tst_int%type@,
  @p_money              @tst_foo1.tst_money%type@,
  @p_nchar              @tst_foo1.tst_nchar%type@,
  @p_numeric            @tst_foo1.tst_numeric%type@,
  @p_nvarchar           @tst_foo1.tst_nvarchar%type@,
  @p_real               @tst_foo1.tst_real%type@,
  @p_smalldatetime      @tst_foo1.tst_smalldatetime%type@,
  @p_smallint           @tst_foo1.tst_smallint%type@,
  @p_smallmoney         @tst_foo1.tst_smallmoney%type@,
  @p_time               @tst_foo1.tst_time%type@,
  @p_tinyint            @tst_foo1.tst_tinyint%type@,
  @p_varbinary          @tst_foo1.tst_varbinary%type@,
  @p_varchar            @tst_foo1.tst_varchar%type@
-- type: none
as
insert into TST_FOO1 (tst_bigint,
                      tst_binary,
                      tst_bit,
                      tst_char,
                      tst_date,
                      tst_datetime,
                      tst_datetime2,
                      tst_datetimeoffset,
                      tst_decimal,
                      tst_float,
                      tst_int,
                      tst_money,
                      tst_nchar,
                      tst_ntext,
                      tst_numeric,
                      tst_nvarchar,
                      tst_real,
                      tst_smalldatetime,
                      tst_smallint,
                      tst_smallmoney,
                      tst_time,
                      tst_tinyint,
                      tst_varbinary,
                      tst_varchar)
values (@p_tst_bigint,
        @p_tst_binary,
        @p_tst_bit,
        @p_tst_char,
        @p_tst_date,
        @p_tst_datetime,
        @p_tst_datetime2,
        @p_tst_datetimeoffset,
        @p_tst_decimal,
        @p_tst_float,
        @p_tst_int,
        @p_tst_money,
        @p_tst_nchar,
        @p_tst_numeric,
        @p_tst_nvarchar,
        @p_tst_real,
        @p_tst_smalldatetime,
        @p_tst_smallint,
        @p_tst_smallmoney,
        @p_tst_text,
        @p_tst_time,
        @p_tst_tinyint,
        @p_tst_varbinary,
        @p_tst_varchar);

