/**
 * Test for all possible types of parameters including LOB's.
 *
 * @param @p_bigint         Test parameter for bigint.
 * @param @p_bit            Test parameter for bit.
 * @param @p_char           Test parameter for char.
 * @param @p_date           Test parameter for date.
 * @param @p_datetime       Test parameter for datetime.
 * @param @p_datetime2      Test parameter for datetime2.
 * @param @p_datetimeoffset Test parameter for datetimeoffset.
 * @param @p_decimal        Test parameter for decimal.
 * @param @p_float          Test parameter for float.
 * @param @p_int            Test parameter for int.
 * @param @p_money          Test parameter for money.
 * @param @p_nchar          Test parameter for nchar.
 * @param @p_numeric        Test parameter for numeric.
 * @param @p_real           Test parameter for real.
 * @param @p_smalldatetime  Test parameter for smalldatetime.
 * @param @p_smallint       Test parameter for smallint.
 * @param @p_smallmoney     Test parameter for smallmoney.
 * @param @p_time           Test parameter for time.
 * @param @p_tinyint        Test parameter for tinyint.
 * @param @p_tst_geography  Test parameter for geography.
 * @param @p_tst_geometry   Test parameter for geometry.
 * @param @p_tst_image      Test parameter for image.
 * @param @p_tst_ntext      Test parameter for ntext.
 * @param @p_tst_text       Test parameter for text.
 * @param @p_tst_xml        Test parameter for xml.
 * @param @p_varchar        Test parameter for varchar.
 */
create procedure tst_parameter_type02
  @p_tst_bigint             @tst_foo1.tst_bigint%type@,
  @p_tst_bit                @tst_foo1.tst_bit%type@,
  @p_tst_char               @tst_foo1.tst_char%type@,
  @p_tst_date               @tst_foo1.tst_date%type@,
  @p_tst_datetime           @tst_foo1.tst_datetime%type@,
  @p_tst_datetime2          @tst_foo1.tst_datetime2%type@,
  @p_tst_datetimeoffset     @tst_foo1.tst_datetimeoffset%type@,
  @p_tst_decimal            @tst_foo1.tst_decimal%type@,
  @p_tst_float              @tst_foo1.tst_float%type@,
  @p_tst_geography          @tst_foo1.tst_geography%type@,
  @p_tst_geometry           @tst_foo1.tst_geometry%type@
  @p_tst_image              @tst_foo1.tst_image%type@,
  @p_tst_int                @tst_foo1.tst_int%type@,
  @p_tst_money              @tst_foo1.tst_money%type@,
  @p_tst_nchar              @tst_foo1.tst_nchar%type@,
  @p_tst_ntext              @tst_foo1.tst_ntext%type@,
  @p_tst_numeric            @tst_foo1.tst_numeric%type@,
  @p_tst_nvarchar           @tst_foo1.tst_nvarchar%type@,
  @p_tst_real               @tst_foo1.tst_real%type@,
  @p_tst_smalldatetime      @tst_foo1.tst_smalldatetime%type@,
  @p_tst_smallint           @tst_foo1.tst_smallint%type@,
  @p_tst_smallmoney         @tst_foo1.tst_smallmoney%type@,
  @p_tst_text               @tst_foo1.tst_text%type@,
  @p_tst_time               @tst_foo1.tst_time%type@,
  @p_tst_tinyint            @tst_foo1.tst_tinyint%type@,
  @p_tst_varbinary          @tst_foo1.tst_varbinary%type@,
  @p_tst_varchar            @tst_foo1.tst_varchar%type@,
  @p_tst_xml                @tst_foo1.tst_xml%type@
-- type: none
as
insert into TST_FOO1( tst_bigint,
                      tst_binary,
                      tst_bit,
                      tst_char,
                      tst_date,
                      tst_datetime,
                      tst_datetime2,
                      tst_datetimeoffset,
                      tst_decimal,
                      tst_float,
                      tst_geography,
                      tst_geometry,
                      tst_image,
                      tst_int,
                      tst_money,
                      tst_nchar,
                      tst_ntext,
                      tst_ntext,
                      tst_numeric,
                      tst_nvarchar,
                      tst_real,
                      tst_smalldatetime,
                      tst_smallint,
                      tst_smallmoney,
                      tst_text,
                      tst_time,
                      tst_tinyint,
                      tst_varbinary,
                      tst_varchar,
                      tst_xml )
values( @p_tst_bigint,
        @p_tst_binary,
        @p_tst_bit,
        @p_tst_char,
        @p_tst_date,
        @p_tst_datetime,
        @p_tst_datetime2,
        @p_tst_datetimeoffset,
        @p_tst_decimal,
        @p_tst_float,
        @p_tst_geography,
        @p_tst_geometry,
        @p_tst_image,
        @p_tst_int,
        @p_tst_money,
        @p_tst_nchar,
        @p_tst_ntext,
        @p_tst_numeric,
        @p_tst_nvarchar,
        @p_tst_real,
        @p_tst_smalldatetime,
        @p_tst_smallint,
        @p_tst_smallmoney,
        @p_tst_text,
        @p_tst_text,
        @p_tst_time,
        @p_tst_tinyint,
        @p_tst_varbinary,
        @p_tst_varchar,
        @p_tst_xml );

