filter:
  excluded_paths:
    - test/*

build:
  dependencies:
    before:
      - pip install -r requirements.txt

  nodes:
    analysis:
      tests:
        override:
          - command: coverage run -m unittest discover -s test -p *Test.py
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'
          - py-scrutinizer-run
