filter:
  excluded_paths:
    - test/*

before_commands:
  - sudo pip3 install cleo==0.6.8
  - sudo pip3 install coverage
  - sudo pip3 install PyStratum-Backend

build:
  dependencies:
    before:
      - pip3 install cleo==0.6.8
      - pip3 install coverage
      - pip3 install PyStratum-Backend

  nodes:
    analysis:
      tests:
        override:
          - command: coverage run -m unittest discover -s test -p *Test.py
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'
          - py-scrutinizer-run
