/**
 * Test for designation type singleton0 with BLOB..
 *
 * @param p_count The number of rows selected.
 *                * 0 For a valid test.
 *                * 1 For a valid test.
 *                * 2 For a invalid test.
 * @param p_blob  The BLOB.
 */
create function tst_test_singleton0a_with_lob( p_count int,
                                               p_blob  bytea )
returns refcursor
as $$
declare
  cur refcursor;
-- type: singleton0
begin
  open cur
  for
  select 1
  from   "TST_FOO2"
  where  tst_c00 <= p_count
  ;

  return cur;
end;
$$ language plpgsql;
