/**
 * Test for designation type rows.
 *
 * @param p_count The number of rows selected.
 * @param p_blob  The BLOB.
 */
create function tst_test_rows1_with_lob( p_count int,
                                         p_blob  bytea )
returns refcursor
as $$
declare
  cur refcursor;
-- type: rows
begin
  open cur
  for
  select *
  from   "TST_FOO2"
  where  tst_c00 <= p_count
  ;

  return cur;
end;
$$ language plpgsql;
