/**
 * Test for designation type singleton1.
 *
 * @param p_count The number of rows selected.
 *                * 0 For a invalid test.
 *                * 1 For a valid test.
 *                * 2 For a invalid test.
 */
create function tst_test_singleton1a( p_count int )
returns refcursor
as $$
declare
  cur refcursor;
-- type: singleton1
begin
  open cur
  for
  select 1
  from   "TST_FOO2"
  where  tst_c00 <= p_count
  ;

  return cur;
end;
$$ language plpgsql;
