/**
 * Test for designation type rows_with_key with BLOB.
 *
 * @param p_count The number of rows selected.
 * @param p_blob  The BLOB.
 */
create function tst_test_rows_with_key1_with_lob( p_count int ,
                                                  p_blob  bytea )
returns refcursor
as $$
declare
  cur refcursor;
-- type: rows_with_key tst_c01,tst_c02,tst_c03
begin
  open cur
  for
  select *
  from   tst_foo2
  where  tst_c00 <= p_count
  ;

  return cur;
end;
$$ language plpgsql;
