/**
 * Test for designation type none with BLOB.
 *
 * @param p_count The number of iterations.
 * @param p_blob  The BLOB.
 */
create function tst_test_none_with_lob( p_count bigint,
                                        p_blob  bytea )
returns void
as $$
declare
  l_count bigint default 0;
-- type: none
begin
 drop table if exists TMP_TMP;

 create temporary table TMP_TMP( c bigint );

 while( l_count < p_count )
 loop
   insert into TMP_TMP( c )
   values( l_count )
   ;

   l_count := l_count +1;
 end loop;

 delete from TMP_TMP
 ;
end;
$$ language plpgsql;


