/**
 * Test for all possible types of parameters excluding LOB's.
 *
 * @param @p_tst_bigint     Test parameter for tst_bigint.
 * @param @p_tst_int        Test parameter for tst_int.
 * @param @p_tst_smallint   Test parameter for tst_smallint.
 * @param @p_tst_bit        Test parameter for tst_bit.
 * @param @p_tst_money      Test parameter for tst_money.
 * @param @p_tst_numeric    Test parameter for tst_numeric.
 * @param @p_tst_float    t Test parameter for tst_float.
 * @param @p_tst_real       Test parameter for tst_real.
 * @param @p_tst_date       Test parameter for tst_date.
 * @param @p_tst_timestamp  Test parameter for tst_timestamp.
 * @param @p_tst_time6      Test parameter for tst_time6.
 * @param @p_tst_char       Test parameter for tst_char.
 * @param @p_tst_varchar    Test parameter for tst_varchar.
 * @param @p_tst_text       Test parameter for tst_text.
 * @param @p_tst_bytea      Test parameter for tst_bytea.
 */
create function tst_parameter_types02(
  p_tst_bigint       @tst_foo1.tst_bigint%type@,
  p_tst_int          @tst_foo1.tst_int%type@,
  p_tst_smallint     @tst_foo1.tst_smallint%type@,
  p_tst_bit          @tst_foo1.tst_bit%type@,
  p_tst_money        @tst_foo1.tst_money%type@,
  p_tst_numeric      @tst_foo1.tst_numeric%type@,
  p_tst_float        @tst_foo1.tst_float%type@,
  p_tst_real         @tst_foo1.tst_real%type@,
  p_tst_date         @tst_foo1.tst_date%type@,
  p_tst_timestamp    @tst_foo1.tst_timestamp%type@,
  p_tst_time6        @tst_foo1.tst_time6%type@,
  p_tst_char         @tst_foo1.tst_char%type@,
  p_tst_varchar      @tst_foo1.tst_varchar%type@,
  p_tst_text         @tst_foo1.tst_text%type@,
  p_tst_bytea        @tst_foo1.tst_bytea%type@ )
returns void
as $$
-- type: none
begin
  insert into TST_FOO1 (tst_bigint,
                        tst_int,
                        tst_smallint,
                        tst_bit,
                        tst_money,
                        tst_numeric,
                        tst_float,
                        tst_real,
                        tst_date,
                        tst_timestamp,
                        tst_time6,
                        tst_char,
                        tst_varchar,
                        tst_text,
                        tst_bytea)
  values (tst_bigint,
          tst_int,
          tst_smallint,
          tst_bit,
          tst_money,
          tst_numeric,
          tst_float,
          tst_real,
          tst_date,
          tst_timestamp,
          tst_time6,
          tst_char,
          tst_varchar,
          tst_text,
          tst_bytea);
end;
$$ language plpgsql;
























