/**
 * Test for designation type row1.
 *
 * @param p_count The number of rows selected.
 *                * 0 For a invalid test.
 *                * 1 For a valid test.
 *                * 2 For a invalid test.
 */
create function tst_test_rows1( p_count int )
returns refcursor
as $$
declare
  cur refcursor;
-- type: rows
begin
  open cur
  for
  select *
  from  "TST_FOO2"
  where  tst_c00 <= p_count
  ;

  return cur;
end;
$$ language plpgsql;
