/**
 * Test for designation type singleton1 with BLOB.
 *
 * @param p_count The number of rows selected.
 *                * 0 For a invalid test.
 *                * 1 For a valid test.
 *                * 2 For a invalid test.
 * @param p_blob  The BLOB.
 */
create procedure tst_test_singleton1a_with_lob( p_count int,
                                                p_blob  blob )
reads sql data
-- type: singleton1
begin
  select 1
  from   TST_FOO2
  where  tst_c00 <= p_count
  ;
end
