/**
 * Test for designation type none with BLOB.
 *
 * @param p_count The number of iterations.
 * @param p_blob  The BLOB.
 */
create procedure tst_test_none_with_lob( p_count bigint,
                                         p_blob  blob )
reads sql data
-- type: none
begin
 declare l_count bigint default 0;

 drop temporary table if exists TMP_TMP;

 create temporary table TMP_TMP( c bigint );

 while( l_count < p_count )
 do
   insert into TMP_TMP( c )
   values( l_count )
   ;

   set l_count = l_count +1;
 end while;

 delete from TMP_TMP
 ;
end
