/**
 * Test for sending data larger than max_allowed_packet.
 *
 * @param p_tmp_blob The BLOB larger than max_allowed_packet.
 */
create procedure tst_test_max_allowed_packet( p_tmp_blob longblob )
reads sql data
-- type: singleton1
begin
  drop temporary table if exists TMP_TMP;

  create temporary table TMP_TMP( tmp_blob longblob ) engine=myisam;

  insert into TMP_TMP( tmp_blob )
  values( p_tmp_blob )
  ;

  select crc32(tmp_blob)
  from   TMP_TMP
  ;
end
