/**
 * Test for designation type rows_with_index with BLOB..
 *
 * @param p_count The number of rows selected.
 * @param p_blob  The BLOB.
 */
create procedure tst_test_rows_with_index1_with_lob( p_count int,
                                                     p_blob  blob )
reads sql data
-- type: rows_with_index tst_c01,tst_c02
begin
  select *
  from   TST_FOO2
  where  tst_c00 <= p_count
  ;
end
