/**
 * Test for all possible types of parameters including LOB's.
 *
 * @param p_param00 Test parameter 00.
 * @param p_param01 Test parameter 01.
 * @param p_param02 Test parameter 02.
 * @param p_param03 Test parameter 03.
 * @param p_param04 Test parameter 04.
 * @param p_param05 Test parameter 05.
 * @param p_param06 Test parameter 06.
 * @param p_param07 Test parameter 07.
 * @param p_param08 Test parameter 08.
 * @param p_param09 Test parameter 09.
 * @param p_param10 Test parameter 10.
 * @param p_param11 Test parameter 11.
 * @param p_param12 Test parameter 12.
 * @param p_param13 Test parameter 13.
 * @param p_param14 Test parameter 14.
 * @param p_param15 Test parameter 15.
 * @param p_param16 Test parameter 16.
 * @param p_param17 Test parameter 17.
 * @param p_param18 Test parameter 18.
 * @param p_param19 Test parameter 19.
 * @param p_param20 Test parameter 20.
 * @param p_param21 Test parameter 21.
 * @param p_param22 Test parameter 22.
 * @param p_param23 Test parameter 23.
 * @param p_param24 Test parameter 24.
 * @param p_param25 Test parameter 25.
 * @param p_param26 Test parameter 26.
 * @param p_param27 Test parameter 27.
 */
create procedure tst_parameter_types02( p_param00 @tst_foo1.tst_c00%type@,
                                        p_param01 @tst_foo1.tst_c01%type@,
                                        p_param02 @tst_foo1.tst_c02%type@,
                                        p_param03 @tst_foo1.tst_c03%type@,
                                        p_param04 @tst_foo1.tst_c04%type@,
                                        p_param05 @tst_foo1.tst_c05%type@,
                                        p_param06 @tst_foo1.tst_c06%type@,
                                        p_param07 @tst_foo1.tst_c07%type@,
                                        p_param08 @tst_foo1.tst_c08%type@,
                                        p_param09 @tst_foo1.tst_c09%type@,
                                        p_param10 @tst_foo1.tst_c10%type@,
                                        p_param11 @tst_foo1.tst_c11%type@,
                                        p_param12 @tst_foo1.tst_c12%type@,
                                        p_param13 @tst_foo1.tst_c13%type@,
                                        p_param14 @tst_foo1.tst_c14%type@,
                                        p_param15 @tst_foo1.tst_c15%type@,
                                        p_param16 @tst_foo1.tst_c16%type@,
                                        p_param17 @tst_foo1.tst_c17%type@,
                                        p_param18 @tst_foo1.tst_c18%type@,
                                        p_param19 @tst_foo1.tst_c19%type@,
                                        p_param20 @tst_foo1.tst_c20%type@,
                                        p_param21 @tst_foo1.tst_c21%type@,
                                        p_param22 @tst_foo1.tst_c22%type@,
                                        p_param23 @tst_foo1.tst_c23%type@,
                                        p_param24 @tst_foo1.tst_c24%type@,
                                        p_param25 @tst_foo1.tst_c25%type@,
                                        p_param26 @tst_foo1.tst_c26%type@,
                                        p_param27 @tst_foo1.tst_c27%type@ )
reads sql data
-- type: none
begin
  insert into TST_FOO1( tst_c00
  ,                     tst_c01
  ,                     tst_c02
  ,                     tst_c03
  ,                     tst_c04
  ,                     tst_c05
  ,                     tst_c06
  ,                     tst_c07
  ,                     tst_c08
  ,                     tst_c09
  ,                     tst_c10
  ,                     tst_c11
  ,                     tst_c12
  ,                     tst_c13
  ,                     tst_c14
  ,                     tst_c15
  ,                     tst_c16
  ,                     tst_c17  
  ,                     tst_c18
  ,                     tst_c19
  ,                     tst_c20
  ,                     tst_c21
  ,                     tst_c22
  ,                     tst_c23
  ,                     tst_c24
  ,                     tst_c25
  ,                     tst_c26
  ,                     tst_c27 )
  values( p_param00
  ,       p_param01
  ,       p_param02
  ,       p_param03
  ,       p_param04
  ,       p_param05
  ,       p_param06
  ,       p_param07
  ,       p_param08
  ,       p_param09
  ,       p_param10
  ,       p_param11
  ,       p_param12
  ,       p_param13
  ,       p_param14
  ,       p_param15
  ,       p_param16 
  ,       p_param17 
  ,       p_param18
  ,       p_param19
  ,       p_param20
  ,       p_param21
  ,       p_param22
  ,       p_param23
  ,       p_param24
  ,       p_param25
  ,       p_param26 
  ,       p_param27 )
  ;
end
