/**
 *  Test for designation bulk_insert.
 */
create procedure tst_test_bulk_insert02()
modifies sql data
-- type: bulk_insert TST_TEMPO field1,_,_,field4,field5
begin
  drop temporary table if exists TST_TEMPO;

  create temporary table TST_TEMPO
  (
     tst_col1             int not null,
     tst_col2             int null,
     tst_col3             int null,
     tst_col4             int not null,
     tst_col5             int not null,
     primary key (tst_col1)
  ) engine = memory
  ;
end
