on:
  - "pull_request"
  - "push"

name: "unit"

permissions:
  contents: "read"

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"

    steps:
      - uses: "actions/checkout@v4"

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Display Python version"
        run: "python -c 'import sys; print(sys.version)'"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install .

      - name: "Run tests with pytest"
        run: |
          python -m coverage run -m unittest discover -s test -p *Test.py
          python -m coverage xml

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v4"
        with:
          fail_ci_if_error: true
          files: "test/coverage.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
